import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

const prefix = process.env.NEXT_PUBLIC_BASE_PATH || '';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href={prefix+'/favicon.ico'} />
      </Head>

      <main className={styles.main}>
        <h1>Let`s do this!!!</h1>
        <Link href="https://www.google.com/"><a className={styles.google}>Let`s go to google</a></Link>
        <p>Tots in the hoooouuuse</p>
        <p>Get some !!!</p>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
